-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 001: Initial schema for AI call agent backend
--
-- How to run:
--   Option A (Supabase CLI): supabase db push
--   Option B (Supabase Dashboard): SQL Editor → paste and run this file
--   Option C (psql): psql $DATABASE_URL -f supabase/migrations/001_initial_schema.sql
--
-- HIPAA NOTE: For production with PHI, enable:
--   1. Supabase HIPAA plan (includes signed BAA)
--   2. Column-level encryption on refill_requests.medication_name, .patient_name
--   3. Row Level Security (RLS) on all tables
--   4. Audit logging (already included in audit_logs table)
-- ─────────────────────────────────────────────────────────────────────────────

-- Required extension for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- APPOINTMENTS
-- Records every booking link sent to a caller via SMS.
-- updated_at is managed automatically by trigger below.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS appointments (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  caller_name         TEXT,
  phone               TEXT,
  email               TEXT,
  appointment_type    TEXT,                          -- new_patient | existing_patient | sales | support
  calendly_link       TEXT,
  calendly_event_uuid TEXT,                          -- populated when caller completes booking
  calendly_event_uri  TEXT,
  start_time          TIMESTAMPTZ,
  status              TEXT        DEFAULT 'link_sent', -- link_sent | booked | cancelled | no_show
  raw_payload         JSONB,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- REFILL REQUESTS
-- Prescription refill intake records.
-- ⚠️  Contains PHI — handle with extra care.
-- status is ALWAYS 'needs_staff_review' on insert (enforced in app code too).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS refill_requests (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_name        TEXT,
  date_of_birth       TEXT,                          -- store as text; avoid PII normalization here
  phone               TEXT,
  medication_name     TEXT,
  dosage              TEXT,
  pharmacy            TEXT,
  is_out_of_medication BOOLEAN    DEFAULT FALSE,
  notes               TEXT,
  staff_note          TEXT,                          -- generated by LLM, editable by staff
  status              TEXT        DEFAULT 'needs_staff_review', -- needs_staff_review | approved | denied | pending_callback
  raw_payload         JSONB,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- SALES LEADS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales_leads (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT,
  company     TEXT,
  phone       TEXT,
  email       TEXT,
  interest    TEXT,
  staff_note  TEXT,
  status      TEXT        DEFAULT 'new',  -- new | contacted | qualified | closed_won | closed_lost
  raw_payload JSONB,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- SUPPORT TICKETS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS support_tickets (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name          TEXT,
  phone         TEXT,
  email         TEXT,
  issue_summary TEXT,
  urgency       TEXT        DEFAULT 'normal',  -- low | normal | high
  staff_note    TEXT,
  status        TEXT        DEFAULT 'open',    -- open | in_progress | resolved | closed
  raw_payload   JSONB,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- CALL LOGS
-- One record per completed Vapi call.
-- transcript is NULL by default — enable only with HIPAA-covered storage.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS call_logs (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  vapi_call_id    TEXT        UNIQUE,
  phone           TEXT,
  caller_name     TEXT,
  intent          TEXT,                         -- classified by LLM
  transcript      TEXT,                         -- NULL unless HIPAA BAA is in place
  summary         TEXT,                         -- LLM-generated call summary
  structured_data JSONB,                        -- extracted data, ended_reason, duration
  raw_payload     JSONB,
  created_at      TIMESTAMPTZ DEFAULT NOW()
  -- No updated_at — call logs are append-only
);

-- ─────────────────────────────────────────────────────────────────────────────
-- AUDIT LOGS
-- Append-only record of every significant action taken by the system.
-- Used for compliance, debugging, and security reviews.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  action      TEXT        NOT NULL,             -- e.g. 'refill_request.created'
  entity_type TEXT,                             -- e.g. 'refill_requests'
  entity_id   UUID,                             -- FK to the affected record
  metadata    JSONB,                            -- sanitized context (avoid PHI here)
  created_at  TIMESTAMPTZ DEFAULT NOW()
  -- Append-only — no UPDATE or DELETE allowed (enforce via RLS in production)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- Covering the most common query patterns:
--   - Look up records by phone number
--   - Filter by status (staff dashboards)
--   - Sort by created_at (default list views)
--   - Find appointment by Calendly UUID (webhook matching)
-- ─────────────────────────────────────────────────────────────────────────────

-- appointments
CREATE INDEX IF NOT EXISTS idx_appointments_phone            ON appointments(phone);
CREATE INDEX IF NOT EXISTS idx_appointments_status           ON appointments(status);
CREATE INDEX IF NOT EXISTS idx_appointments_created_at       ON appointments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_appointments_calendly_uuid    ON appointments(calendly_event_uuid);

-- refill_requests
CREATE INDEX IF NOT EXISTS idx_refill_phone                  ON refill_requests(phone);
CREATE INDEX IF NOT EXISTS idx_refill_status                 ON refill_requests(status);
CREATE INDEX IF NOT EXISTS idx_refill_created_at             ON refill_requests(created_at DESC);

-- sales_leads
CREATE INDEX IF NOT EXISTS idx_sales_phone                   ON sales_leads(phone);
CREATE INDEX IF NOT EXISTS idx_sales_status                  ON sales_leads(status);
CREATE INDEX IF NOT EXISTS idx_sales_created_at              ON sales_leads(created_at DESC);

-- support_tickets
CREATE INDEX IF NOT EXISTS idx_support_phone                 ON support_tickets(phone);
CREATE INDEX IF NOT EXISTS idx_support_status                ON support_tickets(status);
CREATE INDEX IF NOT EXISTS idx_support_created_at            ON support_tickets(created_at DESC);

-- call_logs
CREATE INDEX IF NOT EXISTS idx_call_logs_phone               ON call_logs(phone);
CREATE INDEX IF NOT EXISTS idx_call_logs_vapi_call_id        ON call_logs(vapi_call_id);
CREATE INDEX IF NOT EXISTS idx_call_logs_created_at          ON call_logs(created_at DESC);

-- audit_logs
CREATE INDEX IF NOT EXISTS idx_audit_entity_id               ON audit_logs(entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created_at              ON audit_logs(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- UPDATED_AT TRIGGER
-- Automatically sets updated_at = NOW() on every UPDATE.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to every table that has updated_at
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['appointments', 'refill_requests', 'sales_leads', 'support_tickets']
  LOOP
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated_at
       BEFORE UPDATE ON %s
       FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      tbl, tbl
    );
  END LOOP;
END;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS)
-- Uncomment and configure once you have proper auth set up.
-- With service role key, RLS is bypassed — that's intentional for the backend.
-- Client-facing dashboards (Supabase Studio, custom admin UI) should use
-- anon/authenticated keys with RLS enabled.
-- ─────────────────────────────────────────────────────────────────────────────

-- ALTER TABLE appointments        ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE refill_requests     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE sales_leads         ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE support_tickets     ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE call_logs           ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE audit_logs          ENABLE ROW LEVEL SECURITY;

-- Example policy: staff can read all records (requires auth.role() = 'authenticated')
-- CREATE POLICY "staff_read_all" ON refill_requests
--   FOR SELECT TO authenticated USING (true);
